# Get a line break before the prompt and a multi-line format
add_newline = true

# Order of modules rendered in the prompt
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

# Define the right side prompt for execution time and language runtimes
right_format = """$cmd_duration$rust$nodejs$python$golang"""

# Profile & Theme configurations
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "([\\[$all_status$ahead_behind\\]]($style) )"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow) "

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = false

[hostname]
ssh_only = true
format = "on [$hostname](bold yellow) "
disabled = false
